name: auto_get_hot

on:
  schedule:
    - cron: "0 */1 * * *"
  # push:
  #   branches:
  #     - main
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Shanghai
      
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        
    - name: Run .py
      env:
          API_URL: ${{ secrets.API_URL }}  # 将 Secret 注入环境变量
      run: python hot_md_filter.py

    - name: Commit and Push Changes
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if git diff --staged --quiet; then
            echo "没有更改，跳过提交。"
          else
            git commit -m "Add generated files"
            git push
          fi
